### ISSUE TITLE
jack_in stopped working after 4ffeb09a5f88ff43962982a23c82e9670117e658

### ISSUE THREAD

**Issue by fluke777** [gooddata/gooddata-ruby#301]
If you check out this version, jack_in into a project and type anything it returns

```
NoMethodError: undefined method `process_line' for #<Hash:0x00000102756a40>
from /Users/tomassvarovsky/.rvm/gems/ruby-2.1.2/gems/pry-0.10.1/lib/pry/pry_instance.rb:404:in `process_command'
```

Previous version works fine
